scripts

diff --git a/sae-Firewall/manage b/sae-Firewall/manage
--- a/sae-Firewall/manage
+++ b/sae-Firewall/manage
@@ -14,6 +14,7 @@ help() {
   echo "  start_vm    Start a specific VM. (VM_DIR must be set)"
   echo "  destroy_vm  Destroy a specific VM. (VM_DIR must be set)"
   echo "  start_all   Start all VMs."
+  echo "  provision_all   Provision all VMs."
   echo "  destroy_all Destroy all VMs."
 }
 
@@ -33,9 +34,22 @@ start_vm() {
   check_root
   echo "Starting VM: $VM_DIR"
   pushd "$VM_DIR" > /dev/null 2>&1 || { echo "Directory $VM_DIR not found"; return 1; }
-  rmmod kvm_amd  # Disable KVM module because: Stderr: VBoxManage: error: VirtualBox can't enable the AMD-V extension. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE)
-  rmmod kvm
+  rmmod kvm_amd > /dev/null 2>&1  # Disable KVM module because: Stderr: VBoxManage: error: VirtualBox can't enable the AMD-V extension. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE)
+  rmmod kvm > /dev/null 2>&1
   vagrant up --provider=virtualbox
+  popd > /dev/null 2>&1
+}
+
+provision_vm() {
+  if [[ -z "$VM_DIR" ]]; then
+    echo "VM_DIR must be set. Example: VM_DIR=client $0 start_vm"
+    return 1
+  fi
+
+  check_root
+  echo "Starting VM: $VM_DIR"
+  pushd "$VM_DIR" > /dev/null 2>&1 || { echo "Directory $VM_DIR not found"; return 1; }
+  vagrant provision
   popd > /dev/null 2>&1
 }
 
@@ -61,6 +75,16 @@ start_all() {
   VM_DIR="$VM_FIREWALL" start_vm
 }
 
+provision_all() {
+  check_root
+  echo "Provisionning all VMs..."
+  VM_DIR="$VM_CLIENT" provision_vm
+  VM_DIR="$VM_CLIENT_WAN" provision_vm
+  VM_DIR="$VM_SERVER" provision_vm
+  VM_DIR="$VM_FIREWALL" provision_vm
+}
+
+
 destroy_all() {
   check_root
   echo "Destroying all VMs..."
@@ -83,6 +107,9 @@ case "$1" in
     ;;
   start_all)
     start_all
+    ;;
+  provision_all)
+    provision_all
     ;;
   destroy_all)
     destroy_all
